name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: login
      env:
        DOCKER_PASSWORD: ${{  secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{  secrets.DOCKER_USERNAME }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: push
      run: docker push diegovalle/docker-rstanarm:latest
